### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by toasterhacker** [Exspiravit-sh/OpenWindow#1]
when running the module Instagram 
get the following error message:
"line 387 : cd : Server/sites/instagram: no such file or directory"
This message is similar with each of the modules. 
When attempting to start a server, it loops back to the server module . Giving the options to start server , ~> server , Back and exit.

**Comment by Exspiravit-sh** [comment]
It should be working, I've checked through the script and everything seems fine on my end and everything seems to run fine, if you're still having issues then try to remove the repo and re-clone it.

**Comment by Exspiravit-sh** [comment]
Everything should be working, I checked through it and ran it several times, if you're still having issues then delete and re-clone the repository.
